name: generic_api

channels:
  - conda-forge

dependencies:
  - python=3.8
  - pip
  - setuptools
  - wheel
  - tqdm
  - twine
  - autopep8
  - retrying
  - pandas
  - scikit-learn
  - joblib
  - python-multipart
  - pyyaml
  - fastapi
  - uvicorn
  - uvloop
  - gunicorn